name: 'list all defailt github variables'

on: 
   workflow_dispatch:

jobs:
    ubuntu-environment-variables:
      runs-on: ubuntu-latest
      steps:
        - run: env
    window-environment-variables:
      runs-on: windows-latest
      steps:
        - run: env
    macro-environment-variables:
      runs-on: macos-latest
      steps:
        - run: env
        
     
